### ISSUE TITLE
Requirements for Keystore

### ISSUE THREAD

**Issue by hnjksrdf** [sunnymeow/SecureChatSystem#3]
Hi, i have a issue when trying to create a custom key via the keytool.
The .jks generated look different from what is provided in this repo, so i would appreciae if you could mention any detailed instructions/parameters to use when generating a keypair for this.

Thanks

**Comment by zhushenwudi** [comment]
> 

you can see another issue from me

**Comment by Namiko13** [comment]
great thank you

**Comment by hnjksrdf** [comment]
great thank you very much
